version: 2
references: 
  run_tests: &run_tests
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn install
      - run:
          name: test
          command: |
            mkdir -p ~/reports
            yarn test
      - store_test_results:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

jobs:
  build-node4:
    docker:
      - image: circleci/node:4
    <<: *run_tests
  build-node6:
    docker:
      - image: circleci/node:6
    <<: *run_tests
  build-node8:
    docker:
      - image: circleci/node
    <<: *run_tests
  release:
    docker: 
      - image: circleci/node
    steps: 
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run: semantic-release
      - run: yarn docs
      # needs proper NOW setup first
      # - run: yarn docs:publish

workflows:
  version: 2
  build:
    jobs:
      - build-node4
      - build-node6
      - build-node8
      - release:
          requires: 
            - build-node4
            - build-node6
            - build-node8
