version: 2
references: 
  run_tests: &run_tests
    steps:
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run:
          name: test
          command: |
            mkdir -p ~/reports
            yarn test
      - store_test_results:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
    # Removing this for now while I'm testing workflows.
    #   - run: semantic-release
    # Add this in after fan-out.
    #   - run: yarn docs
      # needs proper NOW setup first
      # - run: yarn docs:publish

jobs:
  build-node4:
    docker:
      - image: circleci/node:4
    <<: *run_tests
  build-node6:
    docker:
      - image: circleci/node:6
    <<: *run_tests

workflows:
  version: 2
  build:
    jobs:
      - build-node4
      - build-node6
